
#ifndef __CONFIG_H__
#define __CONFIG_H__

#define PORTAL_NAME "AUTOPOOL_CONFIG"
#define MQTT_CLIENT_NAME "AUTOPOOL"
#define NTPSERVER "pool.ntp.org"
#define GMTOFFSET 3600
#define DAYLIGHTOFFSET 3600

#define PARAMETER_FILENAME "/config.json"
#define PARAMETERS_JSON_MESSAGE_LEN 300
#define MEASURES_JSON_MESSAGE_LEN 300
#define STATE_JSON_MESSAGE_LEN 300

#define MEASURES_UPDATE_MS 2000
#define GRAPH_UPDATE_MS 5000
#define FILTER_CONTROL_UPDATE_MS 5000
#define ORP_CONTROL_UPDATE_MS 5000

#define DEBUG_PIN1 PIN_EXT1

#endif